# Generated by Django 3.2 on 2023-03-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscribers',
        ),
    ]
